(() => {
  'use strict';
  const API_URL = window.AMCC6090_ATTENDANCE_API || '';
  const sessions = [['01','Sep 04'],['02','Sep 11'],['03','Sep 18'],['04','Sep 25'],['05','Oct 02'],['06','Oct 09'],['07','Oct 16'],['08','Oct 23'],['09','Oct 30'],['10','Nov 06'],['11','Nov 13'],['12','Nov 20'],['13','Nov 27']];
  const form = document.getElementById('speaker-form'), card = document.getElementById('speaker-card'), lookupCard = document.getElementById('speaker-lookup-card'), lookupForm = document.getElementById('speaker-lookup-form'), status = document.getElementById('status'), select = document.getElementById('speaker-session'), lookupSelect = document.getElementById('speaker-lookup-session');
  let reserved = [], editing = false, timer;
  function show(message, kind=''){clearTimeout(timer);status.textContent=message;status.className='status show '+kind;timer=setTimeout(()=>status.className='status',5000)}
  async function request(payload){if(!API_URL)throw new Error('The speaker service is not connected yet.');const response=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload),redirect:'follow'});const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||'The request could not be completed.');return result}
  function render(){const signupSessions=sessions.filter(([id])=>id!=='01');select.innerHTML='<option value="">Choose an available date…</option>'+signupSessions.map(([id,date])=>{const held=reserved.find(item=>item.sessionId===id);return '<option value="'+id+'" '+(held&&!editing?'disabled':'')+'>Session '+id+' · '+date+(held?' · Reserved by '+held.name:'')+'</option>'}).join('');const existingIds=new Set(['01',...reserved.map(item=>item.sessionId)]);const existingSessions=sessions.filter(([id])=>existingIds.has(id));lookupSelect.innerHTML='<option value="">Choose an existing sign-up…</option>'+existingSessions.map(([id,date])=>{const held=reserved.find(item=>item.sessionId===id);const name=held?held.name:(id==='01'?'Dengyang Jiang':'');return '<option value="'+id+'">Session '+id+' · '+date+(name?' · '+name:'')+'</option>'}).join('');const open=signupSessions.length-reserved.filter(item=>item.sessionId!=='01').length;document.getElementById('availability-note').textContent=editing?'Update the speaker bio and presentation details, then save.':open+' open seminar '+(open===1?'date remains.':'dates remain.')+' Reserved dates are disabled.'}
  async function refresh(){const code=form.elements.code.value;if(!code){render();return}const result=await request({action:'speaker-list',code});reserved=result.speakers||[];render()}
  function openNew(){editing=false;form.reset();lookupCard.hidden=true;document.getElementById('form-title').textContent='Reserve your slot.';form.querySelector('button').textContent='Reserve seminar →';card.hidden=false;render();card.scrollIntoView({behavior:'smooth',block:'start'})}
  document.getElementById('open-form').addEventListener('click',openNew);
  document.getElementById('edit-form').addEventListener('click',()=>{card.hidden=true;lookupCard.hidden=false;render();lookupCard.scrollIntoView({behavior:'smooth',block:'start'})});
  lookupForm.elements.code.addEventListener('change',async()=>{try{form.elements.code.value=lookupForm.elements.code.value;await refresh()}catch(error){show(error.message,'error')}});
  form.elements.code.addEventListener('change',async()=>{try{await refresh()}catch(error){show(error.message,'error')}});
  lookupForm.addEventListener('submit',async event=>{event.preventDefault();const button=lookupForm.querySelector('button');button.disabled=true;button.textContent='Retrieving…';try{const data=new FormData(lookupForm);const result=await request({action:'speaker-lookup',code:data.get('code'),sessionId:data.get('sessionId')});if(!result.record)throw new Error('No speaker sign-up has been saved for that session yet.');const r=result.record;editing=true;form.reset();form.elements.code.value=data.get('code');form.elements.originalName.value=r.name;form.elements.name.value=r.name;form.elements.bio.value=r.bio||'';form.elements.materialsUrl.value=r.materialsUrl||'';form.elements.materialsNote.value=r.materialsNote||'';render();if(r.sessionId==='01')select.insertAdjacentHTML('afterbegin','<option value="01">Session 01 · Sep 04 · Dengyang Jiang</option>');select.value=r.sessionId;document.getElementById('form-title').textContent='Edit Session '+r.sessionId+'.';form.querySelector('button').textContent='Save changes →';lookupCard.hidden=true;card.hidden=false;card.scrollIntoView({behavior:'smooth',block:'start'})}catch(error){show(error.message,'error')}finally{button.disabled=false;button.textContent='Retrieve existing sign-up →'}});
  form.addEventListener('submit',async event=>{event.preventDefault();const button=form.querySelector('button');button.disabled=true;button.textContent=editing?'Saving…':'Reserving…';try{const data=new FormData(form);const result=await request({action:'speaker-signup',code:data.get('code'),name:data.get('name'),originalName:data.get('originalName'),sessionId:data.get('sessionId'),bio:data.get('bio'),materialsUrl:data.get('materialsUrl'),materialsNote:data.get('materialsNote')});card.hidden=true;document.getElementById('success').hidden=false;document.getElementById('success-time').textContent='Session '+result.sessionId+' · saved '+new Date(result.updatedAt).toLocaleString();form.reset();editing=false;await refresh()}catch(error){show(error.message,'error')}finally{button.disabled=false;button.textContent=editing?'Save changes →':'Reserve seminar →'}});
  document.getElementById('another-session').addEventListener('click',openNew);render();
})();
