(() => {
  'use strict';
  const API_URL = window.AMCC6090_ATTENDANCE_API || '';
  const sessions = [['01','Sep 04'],['02','Sep 11'],['03','Sep 18'],['04','Sep 25'],['05','Oct 02'],['06','Oct 09'],['07','Oct 16'],['08','Oct 23'],['09','Oct 30'],['10','Nov 06'],['11','Nov 13'],['12','Nov 20'],['13','Nov 27']];
  const form = document.getElementById('speaker-form'), card = document.getElementById('speaker-card'), choice = document.getElementById('speaker-choice'), status = document.getElementById('status'), select = document.getElementById('speaker-session');
  let reserved = [], editing = false, timer;
  function show(message, kind=''){clearTimeout(timer);status.textContent=message;status.className='status show '+kind;timer=setTimeout(()=>status.className='status',5000)}
  async function request(payload){if(!API_URL)throw new Error('The speaker service is not connected yet.');const response=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload),redirect:'follow'});const result=await response.json();if(!response.ok||!result.ok)throw new Error(result.error||'The request could not be completed.');return result}
  function render(){const signupSessions=sessions.filter(([id])=>id!=='01');if(editing){const existingIds=new Set(['01',...reserved.map(item=>item.sessionId)]);select.innerHTML=sessions.filter(([id])=>existingIds.has(id)).map(([id,date])=>{const held=reserved.find(item=>item.sessionId===id);const name=held?held.name:(id==='01'?'Dengyang Jiang':'');return '<option value="'+id+'">Session '+id+' · '+date+(name?' · '+name:'')+'</option>'}).join('');document.getElementById('availability-note').textContent='Choose an existing speaker session, update its details, then save.';return}select.innerHTML='<option value="">Choose an available date…</option>'+signupSessions.map(([id,date])=>{const held=reserved.find(item=>item.sessionId===id);return '<option value="'+id+'" '+(held?'disabled':'')+'>Session '+id+' · '+date+(held?' · Reserved by '+held.name:'')+'</option>'}).join('');const open=signupSessions.length-reserved.filter(item=>item.sessionId!=='01').length;document.getElementById('availability-note').textContent=open+' open seminar '+(open===1?'date remains.':'dates remain.')+' Reserved dates are disabled.'}
  async function refresh(){const result=await request({action:'speaker-public-list'});reserved=result.speakers||[];render()}
  function openNew(){editing=false;form.reset();choice.hidden=true;document.getElementById('form-kicker').textContent='Speaker sign-up';document.getElementById('form-title').textContent='Reserve your slot.';form.querySelector('button').textContent='Reserve seminar →';card.hidden=false;render();card.scrollIntoView({behavior:'smooth',block:'start'})}
  function loadEditRecord(sessionId){const r=reserved.find(item=>item.sessionId===sessionId)||(sessionId==='01'?{sessionId:'01',name:'Dengyang Jiang',bio:'',materialsUrl:'',materialsNote:'Research and internship experience'}:null);if(!r)return;form.elements.originalName.value=r.name;form.elements.name.value=r.name;form.elements.bio.value=r.bio||'';form.elements.materialsUrl.value=r.materialsUrl||'';form.elements.materialsNote.value=r.materialsNote||'';select.value=r.sessionId;document.getElementById('form-title').textContent='Edit Session '+r.sessionId+'.'}
  function openEdit(){editing=true;choice.hidden=true;form.reset();render();loadEditRecord('01');document.getElementById('form-kicker').textContent='Speaker editor';form.querySelector('button').textContent='Save changes →';card.hidden=false;card.scrollIntoView({behavior:'smooth',block:'start'})}
  document.getElementById('open-form').addEventListener('click',openNew);
  document.getElementById('edit-form').addEventListener('click',openEdit);
  select.addEventListener('change',()=>{if(editing)loadEditRecord(select.value)});
  form.addEventListener('submit',async event=>{event.preventDefault();const button=form.querySelector('button');button.disabled=true;button.textContent=editing?'Saving…':'Reserving…';try{const data=new FormData(form);const result=await request({action:'speaker-signup',code:data.get('code'),name:data.get('name'),originalName:data.get('originalName'),sessionId:data.get('sessionId'),bio:data.get('bio'),materialsUrl:data.get('materialsUrl'),materialsNote:data.get('materialsNote')});card.hidden=true;document.getElementById('success').hidden=false;document.getElementById('success-time').textContent='Session '+result.sessionId+' · saved '+new Date(result.updatedAt).toLocaleString();form.reset();editing=false;await refresh()}catch(error){show(error.message,'error')}finally{button.disabled=false;button.textContent=editing?'Save changes →':'Reserve seminar →'}});
  document.getElementById('another-session').addEventListener('click',openNew);
  const requestedMode=new URLSearchParams(location.search).get('mode');
  refresh().then(()=>{if(requestedMode==='reserve')openNew();else if(requestedMode==='edit')openEdit()}).catch(error=>{render();show(error.message,'error')});
})();
